name: Lint and Format

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main


jobs:
    lint-format:
        name: Stylua
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: JohnnyMorganz/stylua-action@v4
              with:
                token: ${{ secrets.GH_TOKEN }}
                version: "0.20.0"
                args: --check lua/ --config-path=stylua.toml

            - name: Luacheck
              uses: lunarmodules/luacheck@v1.2.0
